# General Settings
name: Andreas Weigel
job_title: Softwaredeveloper
email: weigel1986@gmail.com
description: Andreas Weigel ist Softwareentwickler und Berater bei synyx GmbH & Co.KG., wo er seit mehreren Jahren verschiedene Kunden bei der Entwicklung von Softwarelösungen im agilen Umfeld unterstützt. Dabei beschäftigt er sich primär mit Architekturentscheidungen, der vollumfänglichen Automatisierung des Entwicklungsprozesses sowie der Umsetzung von individuellen Lösungen.
avatar: https://s.gravatar.com/avatar/b380f4ffc29403e88d017266b6b5b5a2
favicon: /favicon.ico
twitter_handler: aendi
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'http://twitter.com' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/aendi' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: 'https://stackexchange.com/users/11115276/aendi' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: 'https://www.xing.com/profile/Andreas_Weigel10' }
-  { name: bitcoin, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
